name: Upload to Google Drive

on:
  push:
    branches:
      - main  # Trigger on push to main branch, adjust as necessary

jobs:
  upload-to-drive:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}

    - name: Upload files to Google Drive
      uses: google-github-actions/upload-cloud-storage@v2
      with:
        path: other test/  # Local path in your repository
        destination: gs://1tSEQGxJVkPZTYdGbDJtqGrqC8FQ9bnYD/
