name: Sync Files to Google Drive

on:
  push:
    branches:
      - main

jobs:
  upload-to-drive:
    runs-on: ubuntu-latest  # Specifies the runner environment
    steps:
      - uses: actions/checkout@v2  # Checks-out your repository

      - name: Set up Python
        uses: actions/setup-python@v2  # Sets up Python environment
        with:
          python-version: '3.8'  # Specify the Python version

      - name: Install Google Client Library
        run: pip install --upgrade google-api-python-client google-auth-httplib2 google-auth-oauthlib

      - name: Upload Files to Google Drive
        env:
          GOOGLE_APPLICATION_CREDENTIALS_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
        run: python src/sync_to_gdrive.py  # Replace with your Python script
