name: Upload to Google Drive

on:
  push:
    branches:
      - main

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Upload to Google Drive
        uses: Jodebu/upload-to-drive@master
        with:
          target: README.md
          credentials: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
          folder: 1tSEQGxJVkPZTYdGbDJtqGrqC8FQ9bnYD
